In [7]:
import numpy as np
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y = x%2

In [9]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1])

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [11]:
x_train

array([6, 2, 9, 8, 7, 3])

In [12]:
y_train

array([0, 0, 1, 0, 1, 1])

In [13]:
x_test

array([1, 4, 5])

In [14]:
y_test

array([1, 0, 1])